### ISSUE TITLE
Make "pip install flexpolyline" actually work

### ISSUE THREAD

**Issue by deeplook** [heremaps/flexible-polyline#8]
The claim on https://github.com/heremaps/flexible-polyline/blob/master/python/README.md that `pip install flexpolyline` would work is actually wrong as long as there is no such package distributed to https://pypi.org. What would work is one of these:

```
python setup.py install
pip install -e .
```

**Comment by lene** [comment]
Thank you for raising this issue. Since Flexible Polyline is intended as a reference implementation and not a library, installing it from PyPI does not currently work.

Pushing to PyPI will be implemented in the future due to the demand for it. In the meantime we have updated the documentation to remove the wrong claim, see PR https://github.com/heremaps/flexible-polyline/pull/11

**Comment by lene** [comment]
The `flexpolyline` package has been published on PyPI.
Install it with `$ pip install flexpolyline`.
